"use client";
import { useEffect, useRef, useState } from "react";
import { dataSource } from "../lib/data-source";
import type { Audit, Drone, Incident, Priority } from "../lib/types";

export default function CommandDashboard() {
  const [incidents, setIncidents] = useState<Incident[]>([]), [drones, setDrones] = useState<Drone[]>([]), [audit, setAudit] = useState<Audit[]>([]), [selected, setSelected] = useState<Incident>(), [priority, setPriority] = useState<Priority>(), [offline, setOffline] = useState(false), [voice, setVoice] = useState("Voice ready");
  const peer = useRef<RTCPeerConnection>(), media = useRef<MediaStream>(), callId = useRef(crypto.randomUUID());
  const load = () => Promise.all([dataSource.incidents(), dataSource.drones(), dataSource.audit()]).then(([i, d, a]) => { setIncidents(i); setDrones(d); setAudit(a); setSelected(current => current || i[0]); });
  const makePeer = async () => { if (peer.current) return peer.current; const pc = new RTCPeerConnection({ iceServers: [{ urls: "stun:stun.l.google.com:19302" }] }); peer.current = pc; media.current = await navigator.mediaDevices.getUserMedia({ audio: true }); media.current.getTracks().forEach(track => pc.addTrack(track, media.current!)); pc.onicecandidate = ({ candidate }) => { if (candidate) dataSource.sendVoiceSignal({ type: "ice", call_id: callId.current, payload: candidate.toJSON() }); }; pc.ontrack = ({ streams }) => { const audio = document.getElementById("survivor-audio") as HTMLAudioElement | null; if (audio) { audio.srcObject = streams[0]; audio.play().catch(() => undefined); } setVoice("Voice call connected"); }; return pc; };
  const onSignal = async (signal: any) => { try { if (signal.type === "offer") { callId.current = signal.call_id; const pc = await makePeer(); await pc.setRemoteDescription(signal.payload); const answer = await pc.createAnswer(); await pc.setLocalDescription(answer); dataSource.sendVoiceSignal({ type: "answer", call_id: callId.current, payload: answer }); setVoice("Answering simulated survivor..."); } else if (signal.call_id === callId.current && signal.type === "answer") await (await makePeer()).setRemoteDescription(signal.payload); else if (signal.call_id === callId.current && signal.type === "ice") await (await makePeer()).addIceCandidate(signal.payload); } catch { setVoice("Voice fallback: signalling failed. Use the radio/phone channel."); } };
  useEffect(() => { setOffline(!navigator.onLine); load(); const online = () => setOffline(false), off = () => setOffline(true); addEventListener("online", online); addEventListener("offline", off); const stop = dataSource.subscribe(async (event, payload) => { if (event === "network.offline") setOffline(true); if (event === "network.reconnected") setOffline(false); if (event.startsWith("drone.")) setDrones(current => { const old = current.find(x => x.drone_id === payload.drone_id); return [...current.filter(x => x.drone_id !== payload.drone_id), { ...old, ...payload }]; }); if (event.startsWith("incident.")) load(); if (event === "voice.signal") await onSignal(payload); }); return () => { removeEventListener("online", online); removeEventListener("offline", off); stop(); peer.current?.close(); media.current?.getTracks().forEach(track => track.stop()); }; }, []);
  useEffect(() => { if (selected) dataSource.priority(selected.id).then(setPriority).catch(() => setPriority(undefined)); }, [selected]);
  const startVoice = async () => { try { const pc = await makePeer(); const offer = await pc.createOffer(); await pc.setLocalDescription(offer); if (!dataSource.sendVoiceSignal({ type: "offer", call_id: callId.current, payload: offer })) throw Error(); setVoice("Calling simulated survivor..."); } catch { setVoice("Voice fallback: microphone or realtime gateway unavailable. Use the radio/phone channel."); } };
  return <main><audio id="survivor-audio" autoPlay /><header><h1>RESQNET <small>COMMAND</small></h1><span className={offline ? "offline" : "online"}>{offline ? "OFFLINE - edge buffer active" : "LIVE - synchronized"}</span></header>{offline && <div className="banner">Connectivity lost. Telemetry and incidents remain ordered in the edge buffer and will sync on reconnect.</div>}<section className="grid"><div className="map"><h2>Live mission map</h2><div className="mapboard">{drones.map((d, i) => <button key={d.drone_id} className="drone" style={{ left: `${18 + i * 27}%`, top: `${22 + i * 21}%` }}>▲ {d.drone_id}</button>)}{incidents.map((i, n) => <button key={i.id} onClick={() => setSelected(i)} className="marker" style={{ left: `${40 + n * 18}%`, top: `${55 - n * 14}%` }}>● {i.incidentId}</button>)}</div><p>Three sectors · live telemetry and incident coordinates.</p></div><aside><h2>Drones</h2>{drones.map(d => <div className="card" key={d.drone_id}><b>{d.drone_id}</b><span>{d.sector_id} · {d.status || "connected"}</span></div>)}<button onClick={startVoice}>Connect survivor voice</button><p>{voice}</p></aside></section><section className="grid lower"><div><h2>Incidents</h2>{incidents.map(i => <button className="incident" onClick={() => setSelected(i)} key={i.id}><b>{i.incidentId}</b><span>P{i.priorityScore} · {i.sectorId} · {i.status}</span></button>)}</div><div>{selected && <><h2>{selected.incidentId} detail</h2><div className="card"><b>{selected.survivorCountEstimate} survivor(s), {Math.round(selected.confidence * 100)}% confidence</b><p>{selected.latitude}, {selected.longitude}</p><p>Evidence: {selected.evidence.map(e => e.frame_ref).join(", ")}</p><h3>Priority transparency</h3>{priority ? Object.entries(priority.breakdown).map(([k, v]) => <p key={k}>{k}: <b>{v}</b></p>) : <p>Priority breakdown unavailable.</p>}</div></>}</div><div><h2>Audit log</h2>{audit.slice(0, 5).map(a => <p className="audit" key={a.id}><b>{a.action}</b><br /><small>{a.timestamp}</small></p>)}</div></section></main>;
}
